#! /bin/bash
Green="\e[32m"; 
STD="\033[0;0;39m"; 
wget -O /bin/farfirewall https://raw.githubusercontent.com/barbosafrancakf/BASH/master/farfirewall/farfirewall.sh
chmod +x /bin/farfirewall
mkdir /etc/farfirewall/
mkdir /etc/farfirewall/options/
wget -O /etc/farfirewall/options/allow https://raw.githubusercontent.com/barbosafrancakf/BASH/master/farfirewall/allow.sh
wget -O /etc/farfirewall/options/block https://raw.githubusercontent.com/barbosafrancakf/BASH/master/farfirewall/block.sh
wget -O /etc/farfirewall/options/standard https://raw.githubusercontent.com/barbosafrancakf/BASH/master/farfirewall/standard.sh
wget -O /etc/farfirewall/options/advanced https://raw.githubusercontent.com/barbosafrancakf/BASH/master/farfirewall/advanced.sh
wget -O /etc/farfirewall/options/limit https://raw.githubusercontent.com/barbosafrancakf/BASH/master/farfirewall/limit.sh
echo -e "${Green}[farfirewall]${STD} Installation completed, loading menu..."
farfirewall
