#! /bin/bash
author="@barbosafrancakf";
RED="\033[31m";
Yellow="\033[33m";
BWhite="\033[1m";
Green="\e[32m";
Blue="\033[0;36m";
STD="\033[0;0;39m";
Brown="\033[0;33m";
White="\e[4m";
date=$(date +"%m %B, %Y %H:%M %p");
ip=$(hostname  -I | cut -f1 -d' ');
scriptname="lynxmonitor";
servername="$(hostname)";
operatingsystem="$(lsb_release -si)";
operatingsystemrelease="$(lsb_release -sr)";
bits="$(uname -m | sed "s/x86_//;s/i[3-6]86/32/")";

echo -e "${Green}[UPDATES]${STD} Listing LINUX ${Green}UP${RED}DA${STD}TES..."
apt-get -y update &> /dev/null
apt-get install curl &> /dev/null
echo -e "${Green}[UPDATES]${STD} Installing LINUX ${Green}UP${RED}DA${STD}TES..."
apt-get -y upgrade &> /dev/null
yum -y install pptpd
echo -e "${STD}You're running this script on ${Brown}$operatingsystem $operatingsystemrelease, $bits bits ${STD}"
sleep 0.25
echo -e "${Green}[VPN]${STD} Installing ${Green}PP${RED}TP${STD}..."
apt-get -y install pptpd &> /dev/null
update-rc.d pptpd defaults
echo "localip 192.168.1.50" >> /etc/pptpd.conf
echo "remoteip 192.168.1.60-90" >> /etc/pptpd.conf
echo "ms-dns 8.8.8.8" >> /etc/ppp/pptpd-options
echo "ms-dns 8.8.4.4" >> /etc/ppp/pptpd-options
sleep 1.34 
echo -e "Hey, enter username you should use to connect on ${Green}PP${RED}TP${STD} VPN: "
read username
echo -e "Hello, enter password you should use to connect on ${Green}PP${RED}TP${STD} VPN: " 
read password
echo "$username * $password *" >> /etc/ppp/chap-secrets
echo -e "${Green}[VPN]${STD} Setuping ${Green}U${Yellow}S${Brown}ERS${STD}..."
sleep 1.34
echo -e "${Green}[VPN]${STD} Enabling ${Green}PP${RED}TP${STD}..."
service pptpd restart
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
sysctl -p
echo -e "Back, Do you want to allow: ${RED}1723${STD}(${Brown}TCP${STD}) ${Green}PORT${STD} on firewall [y/N]" 
read yesorno
case $yesorno in
    [yY][eE][sS]|[yY])	 iptables -I INPUT -p tcp --dport 1723 -j ACCEPT && iptables -I INPUT -p gre -j ACCEPT && iptables -t nat -I POSTROUTING -j MASQUERADE;;
    *);;
esac
service pptpd restart
echo -e "Finally, Now you can connect to ${RED}$ip ${STD}using ${Green}$username ${STD}and ${Brown}$password${STD}"
